version: "3.8"
services:
  postgres:
    image: postgres:13
    volumes:
      - il-postgres:/var/lib/postgresql/data
      - ./init-scripts/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  app:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@postgres:5432
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
      - USERS_DB=users
      - COMMENTS_DB=comments
      - GATEWAY_PORT=3000
      - USERS_URL=localhost:3001
      - COMMENTS_URL=localhost:3002
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  il-postgres:
